// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtAi6t3gOr6OonG7ExuZ3rubr3Tq2ZQBc',
    appId: '1:1079524859740:web:b0cf14f8808fe23271ab99',
    messagingSenderId: '1079524859740',
    projectId: 'feed-the-future',
    authDomain: 'feed-the-future.firebaseapp.com',
    storageBucket: 'feed-the-future.firebasestorage.app',
    measurementId: 'G-8QRJS9GT4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe2_DwRAkYUcnIyitIQpigxVZsatqsIEw',
    appId: '1:1079524859740:android:1ddbe7d3fe64370c71ab99',
    messagingSenderId: '1079524859740',
    projectId: 'feed-the-future',
    storageBucket: 'feed-the-future.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaF60KLtnAKZVlomM0tYtVa5kJaTu0ag4',
    appId: '1:1079524859740:ios:aa1f93dd2b468cab71ab99',
    messagingSenderId: '1079524859740',
    projectId: 'feed-the-future',
    storageBucket: 'feed-the-future.firebasestorage.app',
    iosBundleId: 'com.example.androidstudioprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaF60KLtnAKZVlomM0tYtVa5kJaTu0ag4',
    appId: '1:1079524859740:ios:aa1f93dd2b468cab71ab99',
    messagingSenderId: '1079524859740',
    projectId: 'feed-the-future',
    storageBucket: 'feed-the-future.firebasestorage.app',
    iosBundleId: 'com.example.androidstudioprojects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtAi6t3gOr6OonG7ExuZ3rubr3Tq2ZQBc',
    appId: '1:1079524859740:web:5a43e325b921e20471ab99',
    messagingSenderId: '1079524859740',
    projectId: 'feed-the-future',
    authDomain: 'feed-the-future.firebaseapp.com',
    storageBucket: 'feed-the-future.firebasestorage.app',
    measurementId: 'G-W6ZMZ8G5M6',
  );
}
